# Generated by Django 6.1 on 2026-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='branch_access',
            field=models.ManyToManyField(to='organizations.branch'),
        ),
    ]
