# Generated by Django 6.1 on 2026-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='branch',
        ),
    ]
